### ISSUE TITLE
Does not work with TypeScript ES modules

### ISSUE THREAD

**Issue by noraesae** [timoxley/keycode#40]
```typescript
// in TypeScript
import * as keycode from 'keycode';
```

The code above results in `error TS2307: Cannot find module 'keycode'.`

The `tsc` version is v2.4.1.

**Comment by nkint** [comment]
here too

**Comment by wachunga** [comment]
Works fine for me, typescript 2.6.1.
```ts
import keycode from 'keycode';
```

**Comment by gorshkov-leonid** [comment]
does not work with typescript 3.0.3. Maybe you should use "module" as "main" in package.json
